<a href="https://colab.research.google.com/github/rifat2375/Machine-Learning/blob/main/Logical_Regrassion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [99]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [100]:
dataset=pd.read_csv("/content/Movie_classification2375.csv")

In [101]:
dataset.isnull().sum()

Marketing expense      0
Production expense     0
Multiplex coverage     0
Budget                 0
Movie_length           0
Lead_ Actor_Rating     0
Lead_Actress_rating    0
Director_rating        0
Producer_rating        0
Critic_rating          0
Trailer_views          0
Time_taken             0
Twitter_hastags        0
Avg_age_actors         0
Num_multiplex          0
Collection             0
Start_Tech_Oscar       0
Genre                  0
dtype: int64

In [106]:
dataset

Marketing expense  Production expense  ...  Start_Tech_Oscar     Genre
0              20.1264               59.62  ...                 1  Thriller
1              20.5462               69.14  ...                 0     Drama
2              20.5458               69.14  ...                 1    Comedy
3              20.6474               59.36  ...                 1     Drama
4              21.3810               59.36  ...                 1     Drama
..                 ...                 ...  ...               ...       ...
501            21.2526               78.86  ...                 0    Action
502            20.9054               78.86  ...                 0    Action
503            21.2152               78.86  ...                 0    Comedy
504            22.1918               78.86  ...                 0    Comedy
505            20.9482               78.86  ...                 0    Comedy

[506 rows x 18 columns]

In [107]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 17].values

In [108]:
X

array([[2.01264e+01, 5.96200e+01, 4.62000e-01, ..., 4.94000e+02,
        4.80000e+04, 1.00000e+00],
       [2.05462e+01, 6.91400e+01, 5.31000e-01, ..., 4.62000e+02,
        4.32000e+04, 0.00000e+00],
       [2.05458e+01, 6.91400e+01, 5.31000e-01, ..., 4.58000e+02,
        6.94000e+04, 1.00000e+00],
       ...,
       [2.12152e+01, 7.88600e+01, 4.27000e-01, ..., 5.76000e+02,
        4.78000e+04, 0.00000e+00],
       [2.21918e+01, 7.88600e+01, 4.27000e-01, ..., 6.07000e+02,
        4.40000e+04, 0.00000e+00],
       [2.09482e+01, 7.88600e+01, 4.27000e-01, ..., 6.04000e+02,
        3.80000e+04, 0.00000e+00]])

In [109]:
y

array(['Thriller', 'Drama', 'Comedy', 'Drama', 'Drama', 'Comedy',
       'Thriller', 'Drama', 'Comedy', 'Thriller', 'Drama', 'Action',
       'Action', 'Comedy', 'Comedy', 'Thriller', 'Comedy', 'Drama',
       'Action', 'Action', 'Action', 'Comedy', 'Thriller', 'Drama',
       'Drama', 'Thriller', 'Drama', 'Drama', 'Thriller', 'Thriller',
       'Drama', 'Comedy', 'Thriller', 'Comedy', 'Comedy', 'Thriller',
       'Comedy', 'Thriller', 'Thriller', 'Thriller', 'Thriller', 'Action',
       'Thriller', 'Thriller', 'Thriller', 'Thriller', 'Drama',
       'Thriller', 'Comedy', 'Action', 'Thriller', 'Drama', 'Thriller',
       'Thriller', 'Comedy', 'Thriller', 'Drama', 'Drama', 'Comedy',
       'Comedy', 'Thriller', 'Thriller', 'Comedy', 'Action', 'Action',
       'Thriller', 'Action', 'Thriller', 'Thriller', 'Drama', 'Thriller',
       'Action', 'Thriller', 'Drama', 'Thriller', 'Comedy', 'Comedy',
       'Thriller', 'Drama', 'Action', 'Drama', 'Drama', 'Thriller',
       'Drama', 'Drama', '

In [127]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [128]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 50)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=50,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [129]:
y_pred = classifier.predict(X_test)

In [130]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[ 1 10  3  4]
 [ 2 18  5 23]
 [ 1  3  0 21]
 [ 0 14  2 20]]
Classification Report:
              precision    recall  f1-score   support

      Action       0.25      0.06      0.09        18
      Comedy       0.40      0.38      0.39        48
       Drama       0.00      0.00      0.00        25
    Thriller       0.29      0.56      0.38        36

    accuracy                           0.31       127
   macro avg       0.24      0.25      0.22       127
weighted avg       0.27      0.31      0.27       127

Accuracy: 0.30708661417322836
